In [2]:
num_frames = len(frames)
num_frames_bytes = struct.pack('I', num_frames)
sock.sendto(num_frames_bytes, (udp_ip, udp_port))

error: required argument is not an integer

In [68]:
import socket
import numpy as np
import time

# Địa chỉ IP và cổng của ESP32
UDP_IP = "192.168.1.100" # Địa chỉ IP của ESP32
UDP_PORT = 12345

# Thiết lập socket UDP
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

def send_data(data):
    # Chuyển đổi dữ liệu numpy thành chuỗi
    data_str = data.tostring()
    sock.sendto(data_str, (UDP_IP, UDP_PORT))

# Tạo một mảng numpy có shape (n, 3)
n = 10
data = np.random.rand(n, 3)

while True:
    send_data(data)
    time.sleep(1) # Gửi dữ liệu mỗi giây

/tmp/ipykernel_22044/770778587.py:14: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  data_str = data.tostring()


KeyboardInterrupt: 

In [819]:
import numpy as np
import serial
import struct

# Tạo mảng NumPy
n = 2
#data = np.random.rand(n, 3).astype(np.float32)

# data = np.zeros(3)
# Kích thước của mảng

num_rows = 0
num_cols = 0

data = np.array([[20, 30,2]]).astype(np.float32)
num_rows = data.shape[0]
num_cols = data.shape[1]

# Chuyển mảng thành chuỗi byte
data_bytes = data.tobytes()
# Đóng gói kích thước và dữ liệu
header = struct.pack('<II', num_rows, num_cols)  # <II cho hai số nguyên không dấu 32-bit
data_to_send = header + data_bytes
# Mở cổng serial
ser = serial.Serial('/dev/ttyUSB0', 115200*2)  # Thay 'COM3' bằng cổng serial của bạn
print(data)
# Gửi dữ liệu
ser.write(data_to_send)

# Đóng cổng serial
ser.close()

[[20. 30.  2.]]


In [1]:
import numpy as np
import serial
import struct
import time
# Hàm gửi dữ liệu qua cổng serial
def send_data(data):
    num_rows = data.shape[0]
    num_cols = data.shape[1]
    # Chuyển mảng thành chuỗi byte
    data_bytes = data.tobytes()
    # Đóng gói kích thước và dữ liệu
    header = struct.pack('<II', num_rows, num_cols) # <II cho hai số nguyên không dấu 32-bit
    data_to_send = header + data_bytes
    # Mở cổng serial
    ser = serial.Serial('/dev/ttyUSB0', 115200*2) # Thay 'COM3' bằng cổng serial của bạn
    # Gửi dữ liệu
    ser.write(data_to_send)
    # Đóng cổng serial
    ser.close()
    print("sending : ",data_to_send)

# Hàm scale tọa độ
def scaled_image(coords,  h_new, w_new):
    coords[:, 0] = (coords[:, 0] * w_new).astype(float) # Scale x
    coords[:, 1] = (coords[:, 1] * h_new).astype(float) # Scale y
    return coords

# Tạo test case
def create_test_case(n):
    data = np.random.rand(n, 2).astype(np.float32)  # Tạo tọa độ ngẫu nhiên
    return data

# Hàm chính để test
def main():
    for n in range(20):  # Test với n từ 0 đến 10
        data = create_test_case(n)
        print(f"Original data (n={n}):")
        print(data)
        
        #h_old, w_old = 1080, 1920  # Kích thước ban đầu của ảnh
        h_new, w_new = 64, 256   # Kích thước mới của ảnh
        
        scaled_data = scaled_image(data.copy(),h_new, w_new)
        print(f"Scaled data (n={n}):")
        print(scaled_data)
        
        # Gửi dữ liệu qua cổng serial
        send_data(scaled_data)
        time.sleep(.5)
# if __name__ == "__main__":
#     main()

In [2]:
main()

Original data (n=0):
[]
Scaled data (n=0):
[]
sending :  b'\x00\x00\x00\x00\x02\x00\x00\x00'
Original data (n=1):
[[0.7952344  0.51740974]]
Scaled data (n=1):
[[203.58      33.114223]]
sending :  b'\x01\x00\x00\x00\x02\x00\x00\x00{\x94KC\xf7t\x04B'
Original data (n=2):
[[0.5787392  0.797856  ]
 [0.4455843  0.59625006]]
Scaled data (n=2):
[[148.15724   51.062782]
 [114.06958   38.160004]]
sending :  b'\x02\x00\x00\x00\x02\x00\x00\x00A(\x14CJ@LB\xa0#\xe4B\xd8\xa3\x18B'
Original data (n=3):
[[0.37665036 0.5456375 ]
 [0.7503441  0.90092576]
 [0.7350812  0.60379595]]
Scaled data (n=3):
[[ 96.42249  34.9208 ]
 [192.08809  57.65925]
 [188.18079  38.64294]]
sending :  b'\x03\x00\x00\x00\x02\x00\x00\x00Q\xd8\xc0B\xe6\xae\x0bB\x8d\x16@C\x12\xa3fBH.<C_\x92\x1aB'
Original data (n=4):
[[0.7207956  0.0803334 ]
 [0.6455331  0.05988188]
 [0.20356822 0.18528137]
 [0.13108802 0.83925074]]
Scaled data (n=4):
[[184.52367     5.141338 ]
 [165.25647     3.8324401]
 [ 52.113464   11.858007 ]
 [ 33.558533   5